### PR TITLE
Added SAS Project

### PR DESCRIPTION
**Pull request by gjvdkamp**
Hi all, 

I added a project that can read SAS files (.sas7bdat) natively without the need to install SAS software.
There a still bugs I'll post, maybe other can figure those out.  
Could someone make this into a type provider? I can't seem to get my head around those.

### CODE REVIEW

**Comment by tpetricek** [comment]
Nice, thanks for sharing this! 

I'm currently traveling, but unless someone else does that, I'll have a look and merge the PR when I'm back home (or in one place for a few days :-)). Adding a type provider would be fun!

**Comment by gjvdkamp** [comment]
OK, happy travels! Just discovered the TP starterpack so might be able to beat you to it :)

**Comment by arestenko** [comment]
@gjvdkamp great stuff! 
I've added support for compressed and big-endian SAS files. Largely based on https://bitbucket.org/jaredhobbs/sas7bdat.git (python implementation of SAS reader). I've created PR that kind of includes this one. Check it out.

**Comment by tpetricek** [comment]
If I understand it correctly, this PR has been replaced by #31 which is now merged. Is that correct? If so, it should be OK to close this one...

**Pull request closed without merging**
