### PR TITLE
F# Type Provider for SAS

### PR DESCRIPTION
**Pull request by arestenko**
Added support for compressed files and files with big endianness. Type provider also added.

### CODE REVIEW

**Comment by gjvdkamp** [comment]
Awesome thanks! I'll try it out asap (when I'm no longer bogged down in corporate social calls -_-) !

**Comment by gjvdkamp** [comment]
HI, sily question probably but I;m a noob to Git, how do i get to test this code?

**Comment by tpetricek** [comment]
You can currently get it from @arestenko's repository: https://github.com/arestenko/FSharp.Data.Toolbox (Click "Download ZIP" on the right and build it).

**Comment by tpetricek** [comment]
Somehow, I missed the Github notification about this - sorry :-).

This sounds pretty AMAZING! I'll have a look at the code and see if I have any feedback. It would be awesome if you could add a quick introduction and an example to the documentation. You can just [copy the file with Twitter sample](https://github.com/fsprojects/FSharp.Data.Toolbox/blob/master/docs/content/TwitterProvider.fsx) and follow the formatting used there.

One minor tweak (I'm happy to do this myself though) is to use Paket to reference the ProvidedTypes.fs and ProvidedTypes.fsi. This way we do not have to include them in the project and we'll always get the latest version. See how the R provider [does this](https://github.com/BlueMountainCapital/FSharpRProvider/blob/master/paket.dependencies#L15).

Aside from that, are there any major issues left? If no, I would definitely merge this & release it, so that others can play with this!

**Comment by arestenko** [comment]
@tpetricek, thanks for the links Tomas. I'll look into fixing the docs and references early next week.

**Comment by gjvdkamp** [comment]
Hi Arestenko, Been going through the code looks really good! The endianness was really messing with me. 

Can you give me a quick code sample on how to use the SasProvider? I can;t seem to get my head aorund that. SasFile works but the cherry would obviously be strongly typed access to the columns. 
The I'l start testing this to see if I can find any glitches.

**Comment by arestenko** [comment]
@gjvdkamp you're right, type provider wouldn't make much sense without typed access to columns. It's added now. Please see *SasTypeProviderTest.fsx* for a small example. 
I'm yet to add proper documentation.

**Comment by gjvdkamp** [comment]
Hi arestenko, I 'm starting to get how it works, really cool! Will play with it when I have some more time. Few remarks if you want to beat me to it: 
* Each column now is still the Value discriminated union instead of the (option of) underlying type. 
* Good idea on the option to deal with null 
* I'll profile this against the orignal 'non-provider' type generator, I really wrote that with perf in mind to read entire pages and cast to types in one go (Sas.MetaData.fs line 291). Not sure how that would work with an erasing TP though still trying to get my head around those.
* really cool would be a SasLib<filename> that would get a folder name and generate types for every sasfile in it: 
let myLib = new SasLib<"D:\testdata">
myLib.FileOne.Data |> Seq.SumBy (fun d -> d.Var1 * d.Var2)
That would make transitioning for SAS users easier. 

Again really cool stuff! I see you're from st. Petersburg, do you know Andrey Sirotkin perhaps? (Long shot :)

**Comment by arestenko** [comment]
@gjvdkamp, thanks for the feedback. 

Performance is my priority as well, so please let me know your findings. My tests show that it already works at least not slower than when using "official" ole db drivers.

I had exactly the same idea about SasLib - it's on my to do list. 
I'll probably start working on this as soon as I figure out why the build has started failing on Travis. 

Sorry, don't know the people you mention. There are 5 mln people in St.Pete, slim chance :).

**Comment by arestenko** [comment]
Okay, I did nothing to fix it but somehow today it builds. 

@tpetricek I think it's ready to merge. Please review when you have a chance.

**Comment by arestenko** [comment]
Tomas, let me know if you see any issues.
I can't find an easy way to add SasLib like @gjvdkamp
<https://github.com/gjvdkamp> suggested; seems it calls for generated Type
Provider and not erased like it is now.
But I think this library can be useful to someone even in the current state.

**Comment by tpetricek** [comment]
I finally got back to this, tested it and released it. Really nice work :-) [The package is now on NuGet](https://www.nuget.org/packages/FSharp.Data.Toolbox.Sas).

I did a few minor tweaks, which you can see here: https://github.com/fsprojects/FSharp.Data.Toolbox/pull/33

I'll tweet about this next week (nobody is reading twitter over the weekend... :-)) to let the world know about it! Thanks a lot for an amazing contribution :+1:

**Comment by arestenko** [comment]
Awesome, thanks Tomas!

**Pull request merged**
