### PR TITLE
Attempt to update this to dotnet core

### PR DESCRIPTION
**Pull request by nhirschey**
I'm trying to update this to dotnet core. I think I'm most of the way there, but I'm getting some sort of error when trying to use the type provider from SasTypeProvierTest.fsx (error below). Suggestions to fix?

Error:

SasTypeProviderTest.fsx(2,1): error FS3031: The type provider 'C:\FSharp.Data.Toolbox.NetCore\tests\FSharp.Data.Toolbox.Sas.Tests\../../bin/netcoreapp3.1/FSharp.Data.Toolbox.Sas.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'C:\FSharp.Data.Toolbox.NetCore\tests\FSharp.Data.Toolbox.Sas.Tests\../../bin/netcoreapp3.1/FSharp.Data.Toolbox.Sas.dll' which cannot be loaded or doesn't exist. Could not load type 'System.Reflection.TypeDelegator' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### CODE REVIEW

**Comment by nhirschey** [comment]
The test fsx file for the sas provider now seems to work for me in ionide. So my above problem was an issue with my regular visual studio scripting environment.

I converted BIS, Twitter, and SAS. Everything builds successfully, and I've now confirmed that the SAS type provider reads the acadindx.sas7bdat file. I also confirmed that the SAS provider also worked with some other SAS files that I used.

**Comment by nhirschey** [comment]
Relevant issues:
https://github.com/fsprojects/FSharp.Data.Toolbox/issues/49#issue-228278479
https://github.com/fsprojects/FSharp.Data.Toolbox/issues/51#issue-300423162

**Comment by dsyme** [comment]
So this looks ready to merge?

**Comment by dsyme** [comment]
@nhirschey Can I make you co-admin on this project?

**Comment by nhirschey** [comment]
@dsyme I think it's ready to merge. And feel free to add me as co-admin if you'd like; I'm happy to help where I can.

Status:
- I can successfully build netcore versions of all 3 type providers in VS 2019 without any errors.
- I've tested the dotnet core SAS provider using this repo's tests and against some of my own SAS files/code and it all checks out as working. 
- I have not done any specific testing of the BIS and Twitter providers aside from minor updates to make sure that I can build dotnet core versions without errors.
- I haven't touched the fake build script in this pull request, but I have a separate old pull request working on upgrading fake that I can work on next.

**Pull request merged**
